name: Azure ARM
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

        # Checkout code
      - uses: actions/checkout@v3
      - run: echo "AZURE_RG=ci$(date +%Y%m%d%H%M%S)" >> ${GITHUB_ENV}
        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: |
          EXISTS=$(az group exists --name ${AZURE_RG})
          if [ "${EXISTS}" != "true" ]; then
              az group create --location japaneast --name ${AZURE_RG}
          fi

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.AZURE_RG }}
          template: https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/azuredeploy.json
          parameters: FQDN=${{ env.AZURE_RG }}.skirnir.dev hostname=${{ env.AZURE_RG }} stagingHostname=test-${{ env.AZURE_RG }} adminUsername=nanasess adminPublicKey="${{ secrets.PUBLIC_KEY }}"
          failOnStdErr: false

        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}
      - run: az group delete -y --name ${AZURE_RG} --force-deletion-types Microsoft.Compute/virtualMachines
        if: always()
