name: Azure ARM
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

        # Checkout code
      - uses: actions/checkout@v3
      - run: echo "AZURE_RG=ci$(date +%Y%m%d%H%M%S)" >> ${GITHUB_ENV}
        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: |
          EXISTS=$(az group exists --name ${AZURE_RG})
          if [ "${EXISTS}" != "true" ]; then
              az group create --location japaneast --name ${AZURE_RG}
          fi

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.AZURE_RG }}
          template: https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/azuredeploy.json
          parameters: FQDN=${{ env.AZURE_RG }}.skirnir.dev hostname=${{ env.AZURE_RG }} stagingHostname=test-${{ env.AZURE_RG }} adminUsername=nanasess adminPublicKey="${{ secrets.PUBLIC_KEY }}"
          failOnStdErr: false

      - run: echo "PUBLIC_IP=$(az vm show -d -g ${AZURE_RG} -n ${AZURE_RG} --query publicIps -o tsv)" >> ${GITHUB_ENV}
      - run: echo "KNOWN_HOSTS=$(ssh-keyscan ${PUBLIC_IP})" >> ${GITHUB_ENV}

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ env.KNOWN_HOSTS }}
          config: |
            Host ${{ env.AZURE_RG }}
                Hostname ${{ env.PUBLIC_IP }}
                User nanasess
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: bundle install
      - run: TARGET_HOST=${AZURE_RG} rake spec
      - run: az group delete -y --name ${AZURE_RG} --force-deletion-types Microsoft.Compute/virtualMachines
        if: always()
